package com.postmark.java;

public class PromoEmailTemplet2 {

	//public static String sentTempletContent(PromoTempletFields1 templetFields) {
	public static String sentTempletContent(TempletFields templetFields) {

		return "<!doctype html>"
				+"<html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\">"
				+"	<head>"
				+"		<!-- NAME: SELL PRODUCTS -->"
				+"		<!--[if gte mso 15]>"
				+"		<xml>"
				+"			<o:OfficeDocumentSettings>"
				+"			<o:AllowPNG/>"
				+"			<o:PixelsPerInch>96</o:PixelsPerInch>"
				+"			</o:OfficeDocumentSettings>"
				+"		</xml>"
				+"		<![endif]-->"
				+"		<meta charset=\"UTF-8\">"
				+"        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">"
				+"        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
				+"		<title>*|MC:SUBJECT|*</title>"
				+"    <style type=\"text/css\">"
				+"		p{"
				+"			margin:10px 0;"
				+"			padding:0;"
				+"		}"
				+"		table{"
				+"			border-collapse:collapse;"
				+"		}"
				+"		h1,h2,h3,h4,h5,h6{"
				+"			display:block;"
				+"			margin:0;"
				+"			padding:0;"
				+"		}"
				+"		img,a img{"
				+"			border:0;"
				+"			height:auto;"
				+"			outline:none;"
				+"			text-decoration:none;"
				+"		}"
				+"		body,#bodyTable,#bodyCell{"
				+"			height:100%;"
				+"			margin:0;"
				+"			padding:0;"
				+"			width:100%;"
				+"		}"
				+"		#outlook a{"
				+"			padding:0;"
				+"		}"
				+"		img{"
				+"			-ms-interpolation-mode:bicubic;"
				+"		}"
				+"		table{"
				+"			mso-table-lspace:0pt;"
				+"			mso-table-rspace:0pt;"
				+"		}"
				+"		.ReadMsgBody{"
				+"			width:100%;"
				+"		}"
				+"		.ExternalClass{"
				+"			width:100%;"
				+"		}"
				+"		p,a,li,td,blockquote{"
				+"			mso-line-height-rule:exactly;"
				+"		}"
				+"		a[href^=tel],a[href^=sms]{"
				+"			color:inherit;"
				+"			cursor:default;"
				+"			text-decoration:none;"
				+"		}"
				+"		p,a,li,td,body,table,blockquote{"
				+"			-ms-text-size-adjust:100%;"
				+"			-webkit-text-size-adjust:100%;"
				+"		}"
				+"		.ExternalClass,.ExternalClass p,.ExternalClass td,.ExternalClass div,.ExternalClass span,.ExternalClass font{"
				+"			line-height:100%;"
				+"		}"
				+"		a[x-apple-data-detectors]{"
				+"			color:inherit !important;"
				+"			text-decoration:none !important;"
				+"			font-size:inherit !important;"
				+"			font-family:inherit !important;"
				+"			font-weight:inherit !important;"
				+"			line-height:inherit !important;"
				+"		}"
				+"		.templateContainer{"
				+"			max-width:600px !important;"
				+"		}"
				+"		a.mcnButton{"
				+"			display:block;"
				+"		}"
				+"		.mcnImage{"
				+"			vertical-align:bottom;"
				+"		}"
				+"		.mcnTextContent{"
				+"			word-break:break-word;"
				+"		}"
				+"		.mcnTextContent img{"
				+"			height:auto !important;"
				+"		}"
				+"		.mcnDividerBlock{"
				+"			table-layout:fixed !important;"
				+"		}"
				+"	/*"
				+"	@tab Page"
				+"	@section Heading 1"
				+"	@style heading 1"
				+"	*/"
				+"		h1{"
				+"			/*@editable*/color:#222222;"
				+"			/*@editable*/font-family:Helvetica;"
				+"			/*@editable*/font-size:40px;"
				+"			/*@editable*/font-style:normal;"
				+"			/*@editable*/font-weight:bold;"
				+"			/*@editable*/line-height:150%;"
				+"			/*@editable*/letter-spacing:normal;"
				+"			/*@editable*/text-align:center;"
				+"		}"
				+"	/*"
				+"	@tab Page"
				+"	@section Heading 2"
				+"	@style heading 2"
				+"	*/"
				+"		h2{"
				+"			/*@editable*/color:#222222;"
				+"			/*@editable*/font-family:Helvetica;"
				+"			/*@editable*/font-size:34px;"
				+"			/*@editable*/font-style:normal;"
				+"			/*@editable*/font-weight:bold;"
				+"			/*@editable*/line-height:150%;"
				+"			/*@editable*/letter-spacing:normal;"
				+"			/*@editable*/text-align:left;"
				+"		}"
				+"	/*"
				+"	@tab Page"
				+"	@section Heading 3"
				+"	@style heading 3"
				+"	*/"
				+"		h3{"
				+"			/*@editable*/color:#444444;"
				+"			/*@editable*/font-family:Helvetica;"
				+"			/*@editable*/font-size:22px;"
				+"			/*@editable*/font-style:normal;"
				+"			/*@editable*/font-weight:bold;"
				+"			/*@editable*/line-height:150%;"
				+"			/*@editable*/letter-spacing:normal;"
				+"			/*@editable*/text-align:left;"
				+"		}"
				+"	/*"
				+"	@tab Page"
				+"	@section Heading 4"
				+"	@style heading 4"
				+"	*/"
				+"		h4{"
				+"			/*@editable*/color:#999999;"
				+"			/*@editable*/font-family:Georgia;"
				+"			/*@editable*/font-size:20px;"
				+"			/*@editable*/font-style:italic;"
				+"			/*@editable*/font-weight:normal;"
				+"			/*@editable*/line-height:125%;"
				+"			/*@editable*/letter-spacing:normal;"
				+"			/*@editable*/text-align:left;"
				+"		}"
				+"	/*"
				+"	@tab Header"
				+"	@section Header Container Style"
				+"	*/"
				+"		#templateHeader{"
				+"			/*@editable*/background-color:#transparent;"
				+"			/*@editable*/background-image:none;"
				+"			/*@editable*/background-repeat:no-repeat;"
				+"			/*@editable*/background-position:center;"
				+"			/*@editable*/background-size:cover;"
				+"			/*@editable*/border-top:0;"
				+"			/*@editable*/border-bottom:0;"
				+"			/*@editable*/padding-top:22px;"
				+"			/*@editable*/padding-bottom:22px;"
				+"		}"
				+"	/*"
				+"	@tab Header"
				+"	@section Header Interior Style"
				+"	*/"
				+"		.headerContainer{"
				+"			/*@editable*/background-color:#transparent;"
				+"			/*@editable*/background-image:none;"
				+"			/*@editable*/background-repeat:no-repeat;"
				+"			/*@editable*/background-position:center;"
				+"			/*@editable*/background-size:cover;"
				+"			/*@editable*/border-top:0;"
				+"			/*@editable*/border-bottom:0;"
				+"			/*@editable*/padding-top:0;"
				+"			/*@editable*/padding-bottom:0;"
				+"		}"
				+"	/*"
				+"	@tab Header"
				+"	@section Header Text"
				+"	*/"
				+"		.headerContainer .mcnTextContent,.headerContainer .mcnTextContent p{"
				+"			/*@editable*/color:#808080;"
				+"			/*@editable*/font-family:Helvetica;"
				+"			/*@editable*/font-size:16px;"
				+"			/*@editable*/line-height:150%;"
				+"			/*@editable*/text-align:left;"
				+"		}"
				+"	/*"
				+"	@tab Header"
				+"	@section Header Link"
				+"	*/"
				+"		.headerContainer .mcnTextContent a,.headerContainer .mcnTextContent p a{"
				+"			/*@editable*/color:#00ADD8;"
				+"			/*@editable*/font-weight:normal;"
				+"			/*@editable*/text-decoration:underline;"
				+"		}"
				+"	/*"
				+"	@tab Body"
				+"	@section Body Container Style"
				+"	*/"
				+"		#templateBody{"
				+"			/*@editable*/background-color:#FFFFFF;"
				+"			/*@editable*/background-image:none;"
				+"			/*@editable*/background-repeat:no-repeat;"
				+"			/*@editable*/background-position:center;"
				+"			/*@editable*/background-size:cover;"
				+"			/*@editable*/border-top:0;"
				+"			/*@editable*/border-bottom:0;"
				+"			/*@editable*/padding-top:54px;"
				+"			/*@editable*/padding-bottom:54px;"
				+"		}"
				+"	/*"
				+"	@tab Body"
				+"	@section Body Interior Style"
				+"	*/"
				+"		.bodyContainer{"
				+"			/*@editable*/background-color:transparent;"
				+"			/*@editable*/background-image:none;"
				+"			/*@editable*/background-repeat:no-repeat;"
				+"			/*@editable*/background-position:center;"
				+"			/*@editable*/background-size:cover;"
				+"			/*@editable*/border-top:0;"
				+"			/*@editable*/border-bottom:0;"
				+"			/*@editable*/padding-top:0;"
				+"			/*@editable*/padding-bottom:0;"
				+"		}"
				+"	/*"
				+"	@tab Body"
				+"	@section Body Text"
				+"	*/"
				+"		.bodyContainer .mcnTextContent,.bodyContainer .mcnTextContent p{"
				+"			/*@editable*/color:#808080;"
				+"			/*@editable*/font-family:Helvetica;"
				+"			/*@editable*/font-size:16px;"
				+"			/*@editable*/line-height:150%;"
				+"			/*@editable*/text-align:left;"
				+"		}"
				+"	/*"
				+"	@tab Body"
				+"	@section Body Link"
				+"	*/"
				+"		.bodyContainer .mcnTextContent a,.bodyContainer .mcnTextContent p a{"
				+"			/*@editable*/color:#00ADD8;"
				+"			/*@editable*/font-weight:normal;"
				+"			/*@editable*/text-decoration:underline;"
				+"		}"
				+"	/*"
				+"	@tab Footer"
				+"	@section Footer Style"
				+"	*/"
				+"		#templateFooter{"
				+"			/*@editable*/background-color:#2a8ebd;"
				+"			/*@editable*/background-image:none;"
				+"			/*@editable*/background-repeat:no-repeat;"
				+"			/*@editable*/background-position:center;"
				+"			/*@editable*/background-size:cover;"
				+"			/*@editable*/border-top:0;"
				+"			/*@editable*/border-bottom:0;"
				+"			/*@editable*/padding-top:45px;"
				+"			/*@editable*/padding-bottom:63px;"
				+"		}"
				+"	/*"
				+"	@tab Footer"
				+"	@section Footer Interior Style"
				+"	*/"
				+"		.footerContainer{"
				+"			/*@editable*/background-color:#2a8ebd;"
				+"			/*@editable*/background-image:none;"
				+"			/*@editable*/background-repeat:no-repeat;"
				+"			/*@editable*/background-position:center;"
				+"			/*@editable*/background-size:cover;"
				+"			/*@editable*/border-top:0;"
				+"			/*@editable*/border-bottom:0;"
				+"			/*@editable*/padding-top:0;"
				+"			/*@editable*/padding-bottom:0;"
				+"		}"
				+"	/*"
				+"	@tab Footer"
				+"	@section Footer Text"
				+"	*/"
				+"		.footerContainer .mcnTextContent,.footerContainer .mcnTextContent p{"
				+"			/*@editable*/color:#FFFFFF;"
				+"			/*@editable*/font-family:Helvetica;"
				+"			/*@editable*/font-size:12px;"
				+"			/*@editable*/line-height:150%;"
				+"			/*@editable*/text-align:center;"
				+"		}"
				+"	/*"
				+"	@tab Footer"
				+"	@section Footer Link"
				+"	*/"
				+"		.footerContainer .mcnTextContent a,.footerContainer .mcnTextContent p a{"
				+"			/*@editable*/color:#FFFFFF;"
				+"			/*@editable*/font-weight:normal;"
				+"			/*@editable*/text-decoration:underline;"
				+"		}"
				+"	@media only screen and (min-width:768px){"
				+"		.templateContainer{"
				+"			width:600px !important;"
				+"		}"
				+"}	@media only screen and (max-width: 480px){"
				+"		body,table,td,p,a,li,blockquote{"
				+"			-webkit-text-size-adjust:none !important;"
				+"		}"
				+"}	@media only screen and (max-width: 480px){"
				+"		body{"
				+"			width:100% !important;"
				+"			min-width:100% !important;"
				+"		}"
				+"}	@media only screen and (max-width: 480px){"
				+"		.mcnImage{"
				+"			width:100% !important;"
				+"		}"
				+"}	@media only screen and (max-width: 480px){"
				+"		.mcnCartContainer,.mcnCaptionTopContent,.mcnRecContentContainer,.mcnCaptionBottomContent,.mcnTextContentContainer,.mcnBoxedTextContentContainer,.mcnImageGroupContentContainer,.mcnCaptionLeftTextContentContainer,.mcnCaptionRightTextContentContainer,.mcnCaptionLeftImageContentContainer,.mcnCaptionRightImageContentContainer,.mcnImageCardLeftTextContentContainer,.mcnImageCardRightTextContentContainer{"
				+"			max-width:100% !important;"
				+"			width:100% !important;"
				+"		}"
				+"}	@media only screen and (max-width: 480px){"
				+"		.mcnBoxedTextContentContainer{"
				+"			min-width:100% !important;"
				+"		}"
				+"}	@media only screen and (max-width: 480px){"
				+"		.mcnImageGroupContent{"
				+"			padding:9px !important;"
				+"		}"
				+"}	@media only screen and (max-width: 480px){"
				+"		.mcnCaptionLeftContentOuter .mcnTextContent,.mcnCaptionRightContentOuter .mcnTextContent{"
				+"			padding-top:9px !important;"
				+"		}"
				+"}	@media only screen and (max-width: 480px){"
				+"		.mcnImageCardTopImageContent,.mcnCaptionBlockInner .mcnCaptionTopContent:last-child .mcnTextContent{"
				+"			padding-top:18px !important;"
				+"		}"
				+"}	@media only screen and (max-width: 480px){"
				+"		.mcnImageCardBottomImageContent{"
				+"			padding-bottom:9px !important;"
				+"		}"
				+"}	@media only screen and (max-width: 480px){"
				+"		.mcnImageGroupBlockInner{"
				+"			padding-top:0 !important;"
				+"			padding-bottom:0 !important;"
				+"		}"
				+"}	@media only screen and (max-width: 480px){"
				+"		.mcnImageGroupBlockOuter{"
				+"			padding-top:9px !important;"
				+"			padding-bottom:9px !important;"
				+"		}"
				+"}	@media only screen and (max-width: 480px){"
				+"		.mcnTextContent,.mcnBoxedTextContentColumn{"
				+"			padding-right:18px !important;"
				+"			padding-left:18px !important;"
				+"		}"
				+"}	@media only screen and (max-width: 480px){"
				+"		.mcnImageCardLeftImageContent,.mcnImageCardRightImageContent{"
				+"			padding-right:18px !important;"
				+"			padding-bottom:0 !important;"
				+"			padding-left:18px !important;"
				+"		}"
				+"}	@media only screen and (max-width: 480px){"
				+"		.mcpreview-image-uploader{"
				+"			display:none !important;"
				+"			width:100% !important;"
				+"		}"
				+"}	@media only screen and (max-width: 480px){"
				+"	/*"
				+"	@tab Mobile Styles"
				+"	@section Heading 1"
				+"	@tip Make the first-level headings larger in size for better readability on small screens."
				+"	*/"
				+"		h1{"
				+"			/*@editable*/font-size:30px !important;"
				+"			/*@editable*/line-height:125% !important;"
				+"		}"
				+"}	@media only screen and (max-width: 480px){"
				+"	/*"
				+"	@tab Mobile Styles"
				+"	@section Heading 2"
				+"	@tip Make the second-level headings larger in size for better readability on small screens."
				+"	*/"
				+"		h2{"
				+"			/*@editable*/font-size:26px !important;"
				+"			/*@editable*/line-height:125% !important;"
				+"		}"
				+"}	@media only screen and (max-width: 480px){"
				+"	/*"
				+"	@tab Mobile Styles"
				+"	@section Heading 3"
				+"	@tip Make the third-level headings larger in size for better readability on small screens."
				+"	*/"
				+"		h3{"
				+"			/*@editable*/font-size:20px !important;"
				+"			/*@editable*/line-height:150% !important;"
				+"		}"
				+"}	@media only screen and (max-width: 480px){"
				+"	/*"
				+"	@tab Mobile Styles"
				+"	@section Heading 4"
				+"	@tip Make the fourth-level headings larger in size for better readability on small screens."
				+"	*/"
				+"		h4{"
				+"			/*@editable*/font-size:18px !important;"
				+"			/*@editable*/line-height:150% !important;"
				+"		}"
				+"}	@media only screen and (max-width: 480px){"
				+"	/*"
				+"	@tab Mobile Styles"
				+"	@section Boxed Text"
				+"	@tip Make the boxed text larger in size for better readability on small screens. We recommend a font size of at least 16px."
				+"	*/"
				+"		.mcnBoxedTextContentContainer .mcnTextContent,.mcnBoxedTextContentContainer .mcnTextContent p{"
				+"			/*@editable*/font-size:14px !important;"
				+"			/*@editable*/line-height:150% !important;"
				+"		}"
				+"}	@media only screen and (max-width: 480px){"
				+"	/*"
				+"	@tab Mobile Styles"
				+"	@section Header Text"
				+"	@tip Make the header text larger in size for better readability on small screens."
				+"	*/"
				+"		.headerContainer .mcnTextContent,.headerContainer .mcnTextContent p{"
				+"			/*@editable*/font-size:16px !important;"
				+"			/*@editable*/line-height:150% !important;"
				+"		}"
				+"}	@media only screen and (max-width: 480px){"
				+"	/*"
				+"	@tab Mobile Styles"
				+"	@section Body Text"
				+"	@tip Make the body text larger in size for better readability on small screens. We recommend a font size of at least 16px."
				+"	*/"
				+"		.bodyContainer .mcnTextContent,.bodyContainer .mcnTextContent p{"
				+"			/*@editable*/font-size:16px !important;"
				+"			/*@editable*/line-height:150% !important;"
				+"		}"
				+"}	@media only screen and (max-width: 480px){"
				+"	/*"
				+"	@tab Mobile Styles"
				+"	@section Footer Text"
				+"	@tip Make the footer content text larger in size for better readability on small screens."
				+"	*/"
				+"		.footerContainer .mcnTextContent,.footerContainer .mcnTextContent p{"
				+"			/*@editable*/font-size:14px !important;"
				+"			/*@editable*/line-height:150% !important;"
				+"		}"
				+"}</style></head>"
				+"    <body>"
				+"        <center>"
				+"            <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" height=\"100%\" width=\"100%\" id=\"bodyTable\">"
				+"                <tr>"
				+"                    <td align=\"center\" valign=\"top\" id=\"bodyCell\">"
				+"                        <!-- BEGIN TEMPLATE // -->"
				+"                        <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">"
				+"							<tr>"
				+"								<td align=\"center\" valign=\"top\" id=\"templateHeader\" data-template-container>"
				+"									<!--[if gte mso 9]>"
				+"									<table align=\"center\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"600\" style=\"width:600px;\">"
				+"									<tr>"
				+"									<td align=\"center\" valign=\"top\" width=\"600\" style=\"width:600px;\">"
				+"									<![endif]-->"
				+"									<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"templateContainer\">"
				+"										<tr>"
				+"                                			<td valign=\"top\" class=\"headerContainer\"><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"mcnImageBlock\" >"
				+"    <tbody class=\"mcnImageBlockOuter\">"
				+"            <tr>"
				+"                <td valign=\"top\" style=\"padding:9px\" class=\"mcnImageBlockInner\">"
				+"                    <table align=\"left\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"mcnImageContentContainer\" style=\"min-width:100%;\">"
				+"                        <tbody><tr>"
				//+"                            <td class=\"mcnImageContent\" valign=\"top\" style=\"padding-right: 9px; padding-left: 9px; padding-top: 0; padding-bottom: 0; text-align:center;\">"
				/*+"                                     <a href=\"http://www.mobiversa.com\" title=\"\" class=\"\" target=\"_blank\">"
				+"                                        <img align=\"center\" alt=\"Mobiversa\" src=\"https://gallery.mailchimp.com/cbd55b255888ca2fcef14be8c/images/5f0f3fef-8d4f-4d96-be5f-60e1d111f1fc.png\" width=\"450\" style=\"max-width:450px; padding-bottom: 0; display: inline !important; vertical-align: bottom;\" class=\"mcnImage\">"
				+"                                    </a>" style=\"min-width:100%;\" */
				
				
				//+"                                        <img align=\"center\" alt=\"Mobiversa\" src=\"cid:mobiversa_logo1\" width=\"450\" style=\"max-width:367px; padding-bottom: 0; display: inline !important; vertical-align: bottom;\" class=\"mcnImage\">"
				
				
				
				//+"                             </td>"
				
				+"                        <td valign=\"top\" class=\"mcnTextContent\" style=\"padding-top:0; padding-right:18px; padding-bottom:9px; padding-left:18px;\">"
				+"                           <div style=\"text-align: center; font-size:25px\"><h1><span style=\"color:#008080\">"/*<span style=\"font-size:52px\">"*/
				//+ "</span>"
				+ templetFields.getMerchantName()+ "</span></h1></div>"
				+"                           <div style=\"text-align: center; font-size:20px\">"
				+ templetFields.getMerchantAddress()+"<br>"
				+ templetFields.getMerchantPhoneno()
				+"</div>"
				
				
				+"                        </td>"
				
				
				+"                        </tr>"
				+"                    </tbody></table>"
				+"                </td>"
				+"            </tr>"
				+"    </tbody>"
				+"</table></td>"
				+"										</tr>"
				+"									</table>"
				+"									<!--[if gte mso 9]>"
				+"									</td>"
				+"									</tr>"
				+"									</table>"
				+"									<![endif]-->"
				+"								</td>"
				+"                            </tr>"
				+"							<tr>"
				+"								<td align=\"center\" valign=\"top\" id=\"templateBody\" data-template-container>"
				+"									<!--[if gte mso 9]>"
				+"									<table align=\"center\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"600\" style=\"width:600px;\">"
				+"									<tr>"
				+"									<td align=\"center\" valign=\"top\" width=\"600\" style=\"width:600px;\">"
				+"									<![endif]-->"
				+"									<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"templateContainer\">"
				+"										<tr>"
				+"                                			<td valign=\"top\" class=\"bodyContainer\"><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"mcnTextBlock\" style=\"min-width:100%;\">"
				+"    <tbody class=\"mcnTextBlockOuter\">"
				+"        <tr>"
				+"            <td valign=\"top\" class=\"mcnTextBlockInner\" style=\"padding-top:9px;\">"
				+"              	<!--[if mso]>"
				+"				<table align=\"left\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" style=\"width:100%;\">"
				+"				<tr>"
				+"				<![endif]-->"
				+"				<!--[if mso]>"
				+"				<td valign=\"top\" width=\"600\" style=\"width:600px;\">"
				+"				<![endif]-->"
				+"                <table  border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"mcnTextBlock\" style=\"min-width:100%;\" class=\"mcnTextContentContainer\">"
				+"                    <tbody><tr>"
				/*+"<tr>"*/
				+"                        <td valign=\"top\" class=\"mcnTextContent\" style=\"padding-top:0; padding-right:18px; padding-bottom:9px; padding-left:18px;\">"
				+"                           <div style=\"text-align: center; font-size:25px\"><h1><span style=\"color:#008080\">"/*<span style=\"font-size:52px\">"*/
				+ "</span></span>"
				+ templetFields.getPromoName()+ "</h1></div>"
				
				
				+"                        </td>"
				+"                    </tr>"
				+"                </tbody></table>"
				+"				<!--[if mso]>"
				+"				</td>"
				+"				<![endif]-->"
				+"				<!--[if mso]>"
				+"				</tr>"
				+"				</table>"
				+"				<![endif]-->"
				+"            </td>"
				+"        </tr>"
				+"    </tbody>"
				+"</table><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"mcnTextBlock\" style=\"min-width:100%;\">"
				+"    <tbody class=\"mcnTextBlockOuter\">"
				+"        <tr>"
				+"            <td valign=\"top\" class=\"mcnTextBlockInner\" style=\"padding-top:9px;\">"
				+"              	<!--[if mso]>"
				+"				<table align=\"left\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" style=\"width:100%;\">"
				+"				<tr>"
				+"				<![endif]-->"
				+"				<!--[if mso]>"
				+"				<td valign=\"top\" width=\"600\" style=\"width:600px;\">"
				+"				<![endif]-->"
				+"                <table align=\"left\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:100%; min-width:100%;\" width=\"100%\" class=\"mcnTextContentContainer\">"
				+"                    <tbody><tr>"
				+"                        <td valign=\"top\" class=\"mcnTextContent\" style=\"padding-top:0; padding-right:18px; padding-bottom:9px; padding-left:18px;\">"
				+"                            <div style=\"text-align: center;\"><span style=\"font-size:20px\"><span style=\"color:#808080\"><strong>"
				+ templetFields.getPromoDesc()+ "</strong></span></span></div>"
				+"                        </td>"
				+"                    </tr>"
				+"                </tbody></table>"
				+"				<!--[if mso]>"
				+"				</td>"
				+"				<![endif]-->"
				+" 				<!--[if mso]>"
				+"				</tr>"
				+"				</table>"
				+"				<![endif]-->"
				+"            </td>"
				+"        </tr>"
				+"    </tbody>"
				+"</table>"
				+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"mcnImageGroupBlock\" >"
				+"    <tbody class=\"mcnImageGroupBlockOuter\" >"
				+"             <tr>"
				+"                <td valign=\"top\" style=\"padding:9px\" class=\"mcnImageGroupBlockInner\">"
				+"                    <table align=\"center\" width=\"600\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"mcnImageGroupContentContainer\">"
				+"                            <tbody><tr>"
				+"                                <td class=\"mcnImageGroupContent\" valign=\"top\" style=\"padding-left: 9px; padding-top: 0; padding-bottom: 0;\" >"
				//+" width=\"800px\" height=\"264\" style=\"max-width:367px; height=\"264\"   style=\" padding-bottom: 0;\" width=\"260px\"height=\"260px\";                                    <img alt=\"\" src=\"https://gallery.mailchimp.com/cbd55b255888ca2fcef14be8c/images/c36cbeb6-d2df-4ec4-864b-8b3eebe459b0.png\" width=\"264\" style=\"max-width:800px; padding-bottom: 0;\" class=\"mcnImage\">"
				
				
				
				
			//	+"                                        <img src=\"cid:promo_image1\" width =\"300\" >"
			+" <img src=\"cid:"+templetFields.getPromoImg1()+"\" width =\"300\" >"
				
				+"                                </td>"


				
				
				+"                                <td class=\"mcnImageGroupContent\" valign=\"top\"  style=\"padding-right:0;padding-top:0;padding-bottom:0; border=\"1px\" solid#ccc; vertical-align= \"middle\" text-align=\"center\">"
				
				//+"                                        <img alt=\"\" src=\"cid:promo_image2\"    style=\" padding-bottom:0;width:300px;height:300px; \";  class=\"mcnImage\">"
			//	+"                                        <img src=\"cid:promo_image2\" width =\"300\" >"
			+" <img src=\"cid:"+templetFields.getPromoImg2()+"\" width =\"300\" >"
				+"                                </td>"
				
				+"                            </tr>"
				
				+"                        </tbody></table>"
				/*+"  <br><br>                  <table align=\"right\" width=\"50%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"mcnImageGroupContentContainer\">"
				+"                            <tbody><tr  width=\"50%\">"
				
				+"                                <td class=\"mcnImageGroupContent\" valign=\"top\" style=\"padding-right: 9px; padding-top: 0; padding-bottom: 0;\"  width=\"50%\">"
				+"                                     width=\"800px\" height=\"264\"   <img alt=\"\" src=\"https://gallery.mailchimp.com/cbd55b255888ca2fcef14be8c/images/6fee023b-fff4-4498-bf2c-596b139bc6ea.png\" width=\"264\" style=\"max-width:367px; padding-bottom: 0;\" class=\"mcnImage\">"
				
				
				+"                                        <img alt=\"\" src=\"cid:promo_image2\"  style=\"max-width:367px; padding-bottom: 0;\" class=\"mcnImage\">"
				
				
				
				
				+"                                </td>"
				+"                            </tr>"
				+"                        </tbody></table>"*/
				+"                </td>"
				+"            </tr>"
				+"    </tbody>"
				+"</table>"
				+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"mcnTextBlock\" style=\"min-width:100%;\">"
				+"    <tbody class=\"mcnTextBlockOuter\">"
				+"        <tr>"
				+"            <td valign=\"top\" class=\"mcnTextBlockInner\" style=\"padding-top:9px;\">"
				+"              	<!--[if mso]>"
				+"				<table align=\"left\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" style=\"width:100%;\">"
				+"				<tr>"
				+"				<![endif]-->"
				+"				<!--[if mso]>"
				+"				<td valign=\"top\" width=\"600\" style=\"width:600px;\">"
				+"				<![endif]-->"
				+"                <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:100%; min-width:100%;\" width=\"100%\" class=\"mcnTextContentContainer\">"
				+"                    <tbody><tr>"
				+"                        <td valign=\"top\" class=\"mcnTextContent\" style=\"padding-top:0; padding-right:18px; padding-bottom:9px; padding-left:18px;\">"
				+"                           <div style=\"text-align: center;\"> <h3><span style=\"font-size:20px;\">Show this promo code&nbsp;during your purchase: "
				+    templetFields.getPromoCode() +"</span></h3></div>"
				+"                        </td>"
				+"                    </tr>"
				+"                </tbody></table>"
				+"				<!--[if mso]>"
				+"				</td>"
				+"				<![endif]-->"
				+" 				<!--[if mso]>"
				+"				</tr>"
				+"				</table>"
				+"				<![endif]-->"
				+"            </td>"
				+"        </tr>"
				+"    </tbody>"
				+"</table><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"mcnDividerBlock\" style=\"min-width:100%;\">"
				+"    <tbody class=\"mcnDividerBlockOuter\">"
				+"        <tr>"
				+"            <td class=\"mcnDividerBlockInner\" style=\"min-width:100%; padding:18px;\">"
				+"                <table class=\"mcnDividerContent\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"min-width:100%;\">"
				+"                    <tbody><tr>"
				+"                        <td>"
				+"                            <span></span>"
				+"                        </td>"
				+"                    </tr>"
				+"                </tbody></table>"
				+"<!--            "
				+"                <td class=\"mcnDividerBlockInner\" style=\"padding: 18px;\">"
				+"                <hr class=\"mcnDividerContent\" style=\"border-bottom-color:none; border-left-color:none; border-right-color:none; border-bottom-width:0; border-left-width:0; border-right-width:0; margin-top:0; margin-right:0; margin-bottom:0; margin-left:0;\" />"
				+"-->"
				+"            </td>"
				+"        </tr>"
				+"    </tbody>"
			/*	+"</table><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"mcnButtonBlock\" style=\"min-width:100%;\">"
				+"    <tbody class=\"mcnButtonBlockOuter\">"
				+"        <tr>"
				+"            <td style=\"padding-top:0; padding-right:18px; padding-bottom:18px; padding-left:18px;\" valign=\"top\" align=\"center\" class=\"mcnButtonBlockInner\">"
				+"                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"mcnButtonContentContainer\" style=\"border-collapse: separate !important;border-radius: 3px;background-color: #E97C28;\">"
				+"                    <tbody>"
				+"                        <tr>"
				+"                            <td align=\"center\" valign=\"middle\" class=\"mcnButtonContent\" style=\"font-family: Helvetica; font-size: 18px; padding: 18px;\">"
				+"                                <a class=\"mcnButton \" title=\"Click For More Information \" href=\"http://\" target=\"_self\" style=\"font-weight: bold;letter-spacing: -0.5px;line-height: 100%;text-align: center;text-decoration: none;color: #FFFFFF;\">Click For More Information </a>"
				+"                            </td>"
				+"                        </tr>"
				+"                    </tbody>"
				+"                </table>"
				+"            </td>"
				+"        </tr>"
				+"    </tbody>"
				+"</table>" */
				+ "</td>"
				+"										</tr>"
				+"									</table>"
				+"									<!--[if gte mso 9]>"
				+"									</td>"
				+"									</tr>"
				+"									</table>"
				+"									<![endif]-->"
				+"								</td>"
				+"                            </tr>"
				
				
				
				
+"  <td align=\"center\">"
+" <table width=\"564\" >"
+"	<tr>"
+"	<td>"//link

+"  <table width=\"564\" style=\"mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;background-color: #2a8ebd;border-top: 0;border-bottom: 0;padding-top: 9px;padding-bottom: 9px;\">"
+"	<tr>"

+" <td>"

//new change

+"                            <center><em>Powered By Mobiversa Sdn Bhd, All rights reserved.</em><br></center>"
//new change
+" <table width=\"50%\" align=\"center\">"
+"	<tr>"
+"	<td>"//link

+"<table align=\"left\" style=\"display: inline;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">"
		  +
		  "                                                <tbody><tr>"
		  +
		  "                                                    <td class=\"mcnFollowContentItemContainer\" valign=\"top\" style=\"padding-right: 10px;padding-bottom: 9px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;\">"
		  +
		  "                                                        <table width=\"100%\" class=\"mcnFollowContentItem\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;\">"
		  +
		  "                                                            <tbody><tr>"
		  +
		  "                                                                <td align=\"left\" valign=\"middle\" style=\"padding-top: 5px;padding-right: 10px;padding-bottom: 5px;padding-left: 9px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;\">"
		  +
		  "                                                                    <table width=\"\" align=\"left\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;\">"
		  +
		  "                                                                        <tbody><tr>"
				+"                                                    <td align=\"center\" valign=\"top\" class=\"mcnFollowIconContent\" style=\"padding-right:10px; padding-bottom:9px;\">"
				+"                                                        <a href=\"www.facebook.com/mobiversa\" target=\"_blank\">"
				
				
				+"															<img src=\"cid:mobi_facebook\" alt=\"Mobiversa Facebook\" class=\"mcnFollowBlockIcon\" width=\"48\" style=\"width:48px; max-width:48px; display:block;\">"
				+"</a>"
		  +"                                                                                </td>"
		  +
		  "                                                                        </tr>"
		  +
		  "                                                                    </tbody></table>"
		  +
		  "                                                                </td>"
		  +
		  "                                                            </tr>"
		  +
		  "                                                        </tbody></table>"
		  + "                                                    </td>"
		  + "                                                </tr>" +
		  "                                            </tbody></table>"
		  

+" </td>"
+" <td>"

 +"<table align=\"left\" style=\"display: inline;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">"
		  +
		  "                                                <tbody><tr>"
		  +
		  "                                                    <td class=\"mcnFollowContentItemContainer\" valign=\"top\" style=\"padding-right: 10px;padding-bottom: 9px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;\">"
		  +
		  "                                                        <table width=\"100%\" class=\"mcnFollowContentItem\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;\">"
		  +
		  "                                                            <tbody><tr>"
		  +
		  "                                                                <td align=\"left\" valign=\"middle\" style=\"padding-top: 5px;padding-right: 10px;padding-bottom: 5px;padding-left: 9px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;\">"
		  +
		  "                                                                    <table width=\"\" align=\"left\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;\">"
		  +
		  "                                                                        <tbody><tr>"
		 +" <td align=\"center\" valign=\"top\" class=\"mcnFollowIconContent\" style=\"padding-right:10px; padding-bottom:9px;\">"
					+"                                                        <a href=\"https://twitter.com/mobiversa\" target=\"_blank\">"
					
					
					+"															<img src=\"cid:mobi_twitter\" alt=\"Mobiversa Twitter\" class=\"mcnFollowBlockIcon\" width=\"48\" style=\"width:48px; max-width:48px; display:block;\">"
					
					
					+"   													  </a>"
					+"                                                    </td>"
		
		  +
		  "                                                                        </tr>"
		  +
		  "                                                                    </tbody></table>"
		  +
		  "                                                                </td>"
		  +
		  "                                                            </tr>"
		  +
		  "                                                        </tbody></table>"
		  + "                                                    </td>"
		  + "                                                </tr>" +
		  "                                            </tbody></table>"

+" </td>"
+" <td>"

+"                                            <table align=\"left\" style=\"display: inline;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">"
  +
  "                                                <tbody><tr>"
  +
  "                                                    <td class=\"mcnFollowContentItemContainer\" valign=\"top\" style=\"padding-right: 10px;padding-bottom: 9px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;\">"
  +
  "                                                        <table width=\"100%\" class=\"mcnFollowContentItem\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;\">"
  +
  "                                                            <tbody><tr>"
  +
  "                                                                <td align=\"left\" valign=\"middle\" style=\"padding-top: 5px;padding-right: 10px;padding-bottom: 5px;padding-left: 9px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;\">"
  +
  "                                                                    <table width=\"\" align=\"left\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;\">"
  +
  "                                                                        <tbody><tr>"
  
  
  +"<td align=\"center\" valign=\"top\" class=\"mcnFollowIconContent\" style=\"padding-right:10px; padding-bottom:9px;\">"
			+"                                                        <a href=\"https://www.instagram.com/mobiversa_mpos/\" target=\"_blank\">"
			
			
			+"															<img src=\"cid:mobi_instagram\" alt=\"Mobiversa Instagram\" class=\"mcnFollowBlockIcon\" width=\"48\" style=\"width:48px; max-width:48px; display:block;\">"
			
			
			+"														  </a>"
			+"                                                    </td>"
 + "                                                                        </tr>"
  +
  "                                                                    </tbody></table>"
  +
  "                                                                </td>"
  +
  "                                                            </tr>"
  +
  "                                                        </tbody></table>"
  + "                                                    </td>"
  + "                                                </tr>" +
  "                                            </tbody></table>"
  			  
+" </td>"
+" <td>"
+"                                            <table align=\"left\" style=\"display: inline;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">"
  +
  "                                                <tbody><tr>"
  +
  "                                                    <td class=\"mcnFollowContentItemContainer\" valign=\"top\" style=\"padding-right: 0;padding-bottom: 9px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;\">"
  +
  "                                                        <table width=\"100%\" class=\"mcnFollowContentItem\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;\">"
  +
  "                                                            <tbody><tr>"
  +
  "                                                                <td align=\"left\" valign=\"middle\" style=\"padding-top: 5px;padding-right: 10px;padding-bottom: 5px;padding-left: 9px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;\">"
  +
  "                                                                    <table width=\"\" align=\"left\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;\">"
  +
  "                                                                        <tbody><tr>"
  +"<td align=\"center\" valign=\"top\" class=\"mcnFollowIconContent\" style=\"padding-right:0; padding-bottom:9px;\">"
			+"                                                        <a href=\"www.mobiversa.com\" target=\"_blank\">"
			
			
			+"															<img src=\"cid:mobiversa_link\" alt=\"Website\" class=\"mcnFollowBlockIcon\" width=\"48\" style=\"width:48px; max-width:48px; display:block;\">"
			
			
			+"														  </a>"
			+"                                                    </td>"
  /*+
  "                                                                                <td width=\"24\" align=\"center\" class=\"mcnFollowIconContent\" valign=\"middle\" style=\"mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;\">"
  +
  "                                                                                    <a href=\"http://www.linkedin.com/company/mobiversa?\" target=\"_blank\" style=\"mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;\"><img width=\"24\" height=\"24\" style=\"display: block;border: 0;height: auto;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;\" src=\"cid:mobi_linkedin\"></a>"
  +
  "                                                                                </td>"*/
  +
  "                                                                        </tr>"
  +
  "                                                                    </tbody></table>"
  +
  "                                                                </td>"
  +
  "                                                            </tr>"
  +
  "                                                        </tbody></table>"
  + "                                                    </td>"
  + "                                                </tr>" +
  "                                            </tbody></table>"

+" </td>"

+"	</tr>"
+"</table>"

+"<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"mcnDividerBlock\" style=\"min-width:100%;\">"
		+"    <tbody class=\"mcnDividerBlockOuter\">"
		+"        <tr>"
		+"            <td class=\"mcnDividerBlockInner\" style=\"min-width:100%; padding:18px;\">"
		+"                <table class=\"mcnDividerContent\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"min-width: 100%;border-top: 2px solid #505050;\">"
		+"                    <tbody><tr>"
		+"                        <td>"
		+"                            <span></span>"
		+"                        </td>"
		+"                    </tr>"
		+"                </tbody></table>"
		+"<!--            "
		+"                <td class=\"mcnDividerBlockInner\" style=\"padding: 18px;\">"
		+"                <hr class=\"mcnDividerContent\" style=\"border-bottom-color:none; border-left-color:none; border-right-color:none; border-bottom-width:0; border-left-width:0; border-right-width:0; margin-top:0; margin-right:0; margin-bottom:0; margin-left:0;\" />"
		+"-->"
		+"            </td>"
		+"        </tr>"
		+"    </tbody>"
		+"</table><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"mcnTextBlock\" style=\"min-width:100%;\">"
		+"    <tbody class=\"mcnTextBlockOuter\">"
		+"        <tr>"
		+"            <td align=\"center\" valign=\"top\" class=\"mcnTextBlockInner\" style=\"padding-top:9px;\">"
		+"              	<!--[if mso]>"
		+"				<table align=\"center\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" style=\"width:100%;\">"
		+"				<tr>"
		+"				<![endif]-->"
		+"				<!--[if mso]>"
		+"				<td valign=\"top\" width=\"600\" style=\"width:600px;\">"
		+"				<![endif]-->"
		+"                <table align=\"left\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:100%; min-width:100%;\" width=\"100%\" class=\"mcnTextContentContainer\">"
		+"                    <tbody><tr>"
		+"                        <td valign=\"top\" align=\"center\" class=\"mcnTextContent\" style=\"padding-top:0; padding-right:18px;color:#FFFFFF; padding-bottom:9px; padding-left:18px;\">"
/*		+"                            <em>Copyright © 2017 Mobiversa Sdn Bhd, All rights reserved.</em><br>"
		+"<br>"
		+"<strong>Our mailing address is:</strong><br>"
		+"<span style=\"color:#FFFFFF\" align=\"center\"><font size=\"2\"><font face=\"Arial,Helvetica,sans-serif\" size=\"2\">#07-01, Wisma UOA Damansara II,&nbsp;No. 6, Changkat Semantan,&nbsp;</font></font><br>"
		+"<font size=\"2\" ><font face=\"Arial,Helvetica,sans-serif\" size=\"2\">Damansara Heights,&nbsp;50490 Kuala Lumpur</font></font></span><br>"
		+"<span style=\"color:#FFFFFF\" align=\"center\">"
		+"Tel (Toll Free):&nbsp;<a data-content=\"1300303060\" data-type=\"phone\" href=\"tel:1300303060\">1300-30-3060&nbsp;</a></span><br>"
		+"<br>"*/
		+"<span style=\"color:#FFFFFF\" align=\"center\">"
		+"Why are you receiving this email?<br>"
		+"<em><u>You received this email because you had made your purchase with one of our merchant via EZYWIRE.</u></em></span><br>"
		+"&nbsp;"
		+"                        </td>"
		+"                    </tr>"
		+"                </tbody></table>"
		+"				<!--[if mso]>"
		+"				</td>"
		+"				<![endif]-->"
		+"				<!--[if mso]>"
		+"				</tr>"
		+"				</table>"
		+"				<![endif]-->"
		+"            </td>"
		+"        </tr>"
		+"    </tbody>"
		+"</table></td>"
		+"										</tr>"
		+"									</table>"
		+"									<!--[if gte mso 9]>"
		+"									</td>"
		+"									</tr>"
		+"									</table>"
		+"									<![endif]-->"
		+"								</td>"
		+"                            </tr>"
		+"                        </table>"
		+"                    </td>"
		+"                </tr>"
		+"            </table>"
		+"        </center>"
		+"    </body>"
		+"</html>";
	}

}
